apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: customer-service-secret
  namespace: hsbc-prod

  labels:
    app.kubernetes.io/name: customer-service
    app.kubernetes.io/part-of: hsbc

spec:
  provider: aws

  parameters:
    usePodIdentity: "true"

    objects: |
      - objectName: "REPLACE_WITH_CUSTOMER_DB_SECRET_ARN"
        objectType: "secretsmanager"

        jmesPath:
          - path: username
            objectAlias: username

          - path: password
            objectAlias: password

  secretObjects:
    - secretName: customer-db-secret
      type: Opaque

      data:
        - objectName: username
          key: username

        - objectName: password
          key: password
